/*
 * Copyright (c) 2020 the Wavr Audio project.
 * This source file, as well as the binaries generated by it,
 * are licensed under MIT.
 */

use smallvec::Array;

use wavr_audio_buffer::AudioBuffer;

use crate::context::AudioContext;

pub trait Effect {
    fn process(&mut self, context: &AudioContext, buffer: &mut AudioBuffer);
}
