/*
 * Copyright (c) 2020 the Wavr Audio project.
 * This source file, as well as the binaries generated by it,
 * are licensed under MIT.
 */

use crate::context::AudioContext;

pub trait Effect {
    fn process(&mut self, context: &AudioContext, data: &mut [f64]);
}
