/*
 * Copyright (c) 2020 the Wavr Audio project.
 * This source file, as well as the binaries generated by it,
 * are licensed under MIT.
 */
//! # The Wavr Audio Engine's Effect trait
//!
//! The effect trait provides the interface between audio effects and the rack. It is planned to
//! support automation and GUI editors.

use wavr_audio_buffer::AudioBuffer;

use crate::context::AudioContext;

/// Effect trait. Provides an interface for audio processing, parameter information and GUI.
pub trait Effect {
    /// Process an audio frame.
    fn process(&mut self, context: &AudioContext, buffer: &mut AudioBuffer);
}
