name: Docs

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: target
          key: ubuntu-test-${{ hashFiles('Cargo.lock') }}
      - name: System dependencies
        run: sudo apt install libgtk-3-dev
      - name: Cargo Docs
        run: cargo doc --all-features
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        with:
          build_dir: target/doc